import os
import subprocess
from pathlib import Path

import pytest

import render_prompts as renderer


def test_render_document_places_harness_fragment_before_core():
    rendered = renderer.render_document(
        fragment="## Codex\ncodex body\n",
        core="# Global\ncore body\n",
        stamp="2026-04-25",
    )

    assert rendered.startswith("<!-- Generated by sync-ai-prompts on 2026-04-25.")
    assert rendered.index("codex body") < rendered.index("core body")
    assert "Edit prompts/core.md and prompts/harnesses/*.md" in rendered
    assert str(Path.home()) not in rendered


def test_render_document_places_private_overlay_after_core():

    rendered = renderer.render_document(
        fragment="## Claude\nclaude body\n",
        core="# Global\ncore body\n",
        private="## Private\nprivate body\n",
        stamp="2026-04-25",
    )

    assert rendered.index("claude body") < rendered.index("core body")
    assert rendered.index("core body") < rendered.index("private body")
    assert "private.example.md" in rendered


def test_harness_catalog_is_the_six_supported_plus_generic():
    harnesses = set(renderer.harness_names())

    assert harnesses == {
        "claude",
        "codex",
        "opencode",
        "commandcode",
        "antigravity",
        "hermes",
        "generic",
    }
    for removed in (
        "gemini",
        "cursor",
        "windsurf",
        "copilot",
        "aider",
        "goose",
        "amp",
        "continue",
        "cline",
        "roo",
        "qwen",
        "warp",
        "kiro",
        "augment",
        "openhands",
        "pi",
        "openclaw",
        "crush",
        "kimi",
        "nanoclaw",
    ):
        assert removed not in harnesses


def test_harness_displays_are_stable():
    harnesses = {harness.name: harness for harness in renderer.HARNESSES}

    assert harnesses["claude"].display == "Claude Code"
    assert harnesses["codex"].display == "OpenAI Codex"
    assert harnesses["opencode"].display == "OpenCode"
    assert harnesses["commandcode"].display == "Command Code"
    assert harnesses["antigravity"].display == "Antigravity"
    assert harnesses["hermes"].display == "Hermes Agent"
    assert harnesses["generic"].display == "Generic AGENTS.md"


def test_harness_support_levels_are_exposed_in_registry():

    levels = {harness.name: harness.support_level for harness in renderer.HARNESSES}

    assert renderer.DEPLOYABLE == "deployable"
    assert renderer.MANUAL == "manual"
    assert renderer.SUPPORT_LEVELS == {"deployable", "manual"}
    assert levels["claude"] == "deployable"
    assert levels["codex"] == "deployable"
    assert levels["opencode"] == "deployable"
    assert levels["commandcode"] == "deployable"
    assert levels["antigravity"] == "deployable"
    assert levels["hermes"] == "manual"
    assert levels["generic"] == "manual"


def test_target_path_uses_home_and_env_override(tmp_path):

    default_path = renderer.target_path("codex", home=tmp_path, env={})
    override_path = renderer.target_path(
        "codex",
        home=tmp_path,
        env={"CODEX_AGENTS_PATH": "/custom/AGENTS.md"},
    )

    assert default_path == tmp_path / ".codex" / "AGENTS.md"
    assert override_path == Path("/custom/AGENTS.md")


def test_manual_target_path_requires_env_override(tmp_path):

    assert renderer.target_path("hermes", home=tmp_path, env={}) is None
    assert renderer.target_path("generic", home=tmp_path, env={}) is None

    assert renderer.target_path(
        "hermes",
        home=tmp_path,
        env={"HERMES_AGENTS_PATH": "/project/HERMES.md"},
    ) == Path("/project/HERMES.md")
    assert renderer.target_path(
        "generic",
        home=tmp_path,
        env={"GENERIC_AGENTS_PATH": "/project/AGENTS.md"},
    ) == Path("/project/AGENTS.md")


def test_harness_target_rows_include_support_level_and_manual_label():

    rows = {
        display: (support, target, notes)
        for display, support, target, notes in renderer.harness_target_rows()
    }

    assert rows["Antigravity"][0] == "deployable"
    assert rows["Antigravity"][1] == "~/.gemini/GEMINI.md"
    assert rows["Hermes Agent"][0] == "manual"
    assert rows["Generic AGENTS.md"][0] == "manual"
    assert "HERMES_HOME" in rows["Hermes Agent"][2]


def test_selected_harnesses_accept_comma_separated_targets():

    selected = renderer.selected_harnesses(["claude,codex", "opencode"])

    assert [harness.name for harness in selected] == ["claude", "codex", "opencode"]


def test_render_all_writes_selected_harnesses_to_output_dir(tmp_path):
    repo = tmp_path / "repo"
    (repo / "prompts" / "harnesses").mkdir(parents=True)
    (repo / "prompts" / "core.md").write_text("# Core\nshared\n", encoding="utf-8")
    (repo / "prompts" / "private.md").write_text("## Private\nlocal only\n", encoding="utf-8")
    (repo / "prompts" / "harnesses" / "claude.md").write_text(
        "## Claude\nclaude only\n",
        encoding="utf-8",
    )
    (repo / "prompts" / "harnesses" / "codex.md").write_text(
        "## Codex\ncodex only\n",
        encoding="utf-8",
    )

    written = renderer.render_all(
        repo_root=repo,
        out_dir=tmp_path / "out",
        selected=["claude", "codex"],
        stamp="2026-04-25",
    )

    assert written == {
        "claude": tmp_path / "out" / "CLAUDE.md",
        "codex": tmp_path / "out" / "AGENTS.md",
    }
    assert "claude only" in written["claude"].read_text(encoding="utf-8")
    assert "shared" in written["codex"].read_text(encoding="utf-8")
    assert "local only" in written["codex"].read_text(encoding="utf-8")


def test_full_catalog_render_places_colliding_outputs_in_harness_subdirectories(tmp_path):
    repo = Path(__file__).resolve().parents[1]

    written = renderer.render_all(
        repo_root=repo,
        out_dir=tmp_path / "out",
        stamp="2026-04-25",
    )
    output_counts = {}
    for harness in renderer.HARNESSES:
        output_counts[harness.output_name] = output_counts.get(harness.output_name, 0) + 1

    for harness, path in written.items():
        item = renderer.harness_by_name(harness)
        if output_counts[item.output_name] > 1:
            assert path == tmp_path / "out" / harness / item.output_name


def test_single_selected_agents_output_stays_top_level(tmp_path):
    repo = Path(__file__).resolve().parents[1]

    written = renderer.render_all(
        repo_root=repo,
        out_dir=tmp_path / "out",
        selected=["codex"],
        stamp="2026-04-25",
    )

    assert written["codex"] == tmp_path / "out" / "AGENTS.md"


def test_apply_optional_blocks_keeps_enabled_and_drops_disabled():
    text = "A\n<!-- optional:subagents -->\nB\n<!-- /optional:subagents -->\nC\n"

    assert "B" in renderer.apply_optional_blocks(text, frozenset({"subagents"}))
    assert "B" not in renderer.apply_optional_blocks(text, frozenset())
    assert "A" in renderer.apply_optional_blocks(text, frozenset())
    assert "C" in renderer.apply_optional_blocks(text, frozenset())


def test_generic_target_drops_the_subagent_delegation_block(tmp_path):
    repo = Path(__file__).resolve().parents[1]

    generic = renderer.render_all(
        repo_root=repo, out_dir=tmp_path / "g", selected=["generic"], stamp="2026-04-25"
    )
    claude = renderer.render_all(
        repo_root=repo, out_dir=tmp_path / "c", selected=["claude"], stamp="2026-04-25"
    )

    assert "## Delegation" not in generic["generic"].read_text(encoding="utf-8")
    assert "## Delegation" in claude["claude"].read_text(encoding="utf-8")


def test_common_guidance_lives_in_core_not_harness_fragments():
    repo = Path(__file__).resolve().parents[1]
    core = (repo / "prompts" / "core.md").read_text(encoding="utf-8")
    harness_text = "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted((repo / "prompts" / "harnesses").glob("*.md"))
    )

    for phrase in (
        "versions, features, pricing, APIs, docs",
        "Functional status markers are fine",
        "Use dense bullet lists",
        "environment scrubbing can hide",
        "user's explicit instructions take precedence over skill guidance",
    ):
        assert phrase in core

    for phrase in (
        "Search the web first for versions",
        "Verify versions, features, pricing, and docs first",
        "Functional status markers are allowed",
        "Prefer dense bullet lists",
        "If subprocess environment scrubbing is enabled",
    ):
        assert phrase not in harness_text


def test_vendor_harnesses_define_model_ladders():
    repo = Path(__file__).resolve().parents[1]

    claude = (repo / "prompts" / "harnesses" / "claude.md").read_text(encoding="utf-8")
    codex = (repo / "prompts" / "harnesses" / "codex.md").read_text(encoding="utf-8")

    assert "Haiku = lower cost/fast" in claude
    assert "Sonnet = balanced default" in claude
    assert "Fable = tier above Opus" in claude
    assert "Luna-class) = lower cost" in codex
    assert "flagship (Sol-class" in codex
    assert "do not freeze stale names" in codex


@pytest.mark.parametrize("harness", ["claude", "codex", "opencode", "commandcode"])
def test_rendered_workflow_policy_covers_aliases_and_indirect_calls(harness):
    repo = Path(__file__).resolve().parents[1]
    rendered = renderer.render_document(
        fragment=(repo / "prompts" / "harnesses" / f"{harness}.md").read_text(),
        core=(repo / "prompts" / "core.md").read_text(),
        stamp="2026-09-10",
    )

    assert "Workflow-style skills are opt-in" in rendered
    assert "aliases and indirect calls from other skills" in rendered
    assert "ordinary brainstorming or implementation requests do not opt in" in rendered
    assert "if a skill could plausibly apply, invoke it first" not in rendered
    assert "proactively when a task touches a skill-adjacent topic" not in rendered
    assert "before starting skill-adjacent work" not in rendered


def test_harness_fragments_track_current_agent_behavior():
    repo = Path(__file__).resolve().parents[1]
    harness_dir = repo / "prompts" / "harnesses"

    claude = (harness_dir / "claude.md").read_text(encoding="utf-8")
    codex = (harness_dir / "codex.md").read_text(encoding="utf-8")
    opencode = (harness_dir / "opencode.md").read_text(encoding="utf-8")

    assert "--safe-mode" in claude
    assert "Auto mode is the default permission mode" in claude
    assert "run in the background by default" in claude
    assert "Untrusted projects do not contribute project-level" in codex
    assert "codex queue" in codex
    assert "Skills are native, no plugin required" in opencode
    assert "opencode.jsonc" in opencode


def test_fragments_track_fable_5_1_and_current_cli_defaults():
    repo = Path(__file__).resolve().parents[1]
    core = (repo / "prompts" / "core.md").read_text(encoding="utf-8")
    claude = (repo / "prompts" / "harnesses" / "claude.md").read_text(encoding="utf-8")
    codex = (repo / "prompts" / "harnesses" / "codex.md").read_text(encoding="utf-8")

    assert "do not map to the same depth across models" in core
    assert "Edit surgically rather than rewriting whole files" in core
    assert "reported as follow-ups, not fixed in the same change" in core
    assert "do not promote scratch checks to permanent test files" in core
    assert "a plan, or a promise about work not yet done" in core

    assert "the default `high` fits most work on Fable 5.1 and Opus 5" in claude
    assert "safeguard false positives" in claude
    assert "When migrating to Astra, preserve effective effort initially" in codex
    assert "do not assume API and app effort ranges match" in codex
    assert "/effort xhigh" not in claude
    assert "--restricted" in claude
    assert "CLAUDE_CODE_SUBAGENT_MODEL" in claude

    assert "`ultra`" in codex
    assert "--approve-for-me" in codex
    assert "`codex mcp-server` is deprecated" in codex
    assert "AGENTS.override.md" in codex


def test_core_tracks_fable_5_1_and_gpt_5_6_prompting_guides():
    repo = Path(__file__).resolve().parents[1]
    core = (repo / "prompts" / "core.md").read_text(encoding="utf-8")
    harness_text = "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted((repo / "prompts" / "harnesses").glob("*.md"))
    )

    for phrase in (
        "Lead with the outcome",
        "not by compressing into fragments",
        "a reader who saw none of the work",
        "## Autonomy",
        "inspect and report",
        "Safe local actions need no confirmation",
        "Finish the whole task",
        "Issue independent tool calls together in one response",
        "Use lists when asked or when the content is multifaceted",
        "compare one level lower",
        "Recognizing a name is not knowing its current state",
        "Keep work you can finish in a handful of tool calls inline",
        "Preserve authorization across turns",
        "Once appropriate checks pass",
        "Keep working while subagents run",
        "when check output would flood the context",
    ):
        assert phrase in core

    assert "narrates and formats less" not in harness_text


def test_kept_harness_fragments_describe_operational_scope():
    repo = Path(__file__).resolve().parents[1]
    harness_dir = repo / "prompts" / "harnesses"

    antigravity = (harness_dir / "antigravity.md").read_text(encoding="utf-8")
    hermes = (harness_dir / "hermes.md").read_text(encoding="utf-8")
    generic = (harness_dir / "AGENTS.md").read_text(encoding="utf-8")

    assert "GEMINI.md" in antigravity
    assert ".agents/rules/" in antigravity
    assert "agent.coding_instructions" in hermes
    assert "AGENTS.override.md" in hermes
    assert "Leave `SOUL.md` alone" in hermes
    assert "GENERIC_AGENTS_PATH" in generic


def test_every_fragment_uses_h2_heading_without_repeated_provenance():
    repo = Path(__file__).resolve().parents[1]

    for path in sorted((repo / "prompts" / "harnesses").glob("*.md")):
        text = path.read_text(encoding="utf-8")
        first_line = text.splitlines()[0]
        assert first_line.startswith("## "), f"{path.name}: heading must be H2 so core headings nest cleanly"
        assert "run `scripts/sync-ai-prompts`" not in text, f"{path.name}: drop the repeated provenance line"


def test_effort_guidance_is_general_with_vendor_caveats():
    repo = Path(__file__).resolve().parents[1]

    core = (repo / "prompts" / "core.md").read_text(encoding="utf-8")
    claude = (repo / "prompts" / "harnesses" / "claude.md").read_text(encoding="utf-8")
    codex = (repo / "prompts" / "harnesses" / "codex.md").read_text(encoding="utf-8")

    assert "Effort names are vendor-specific" in core
    assert "Effort names vary by model" in claude
    assert "Verify current CLI/docs before setting automation flags" in codex


def test_generic_workflow_guidance_stays_in_core():
    repo = Path(__file__).resolve().parents[1]
    core = (repo / "prompts" / "core.md").read_text(encoding="utf-8")
    harness_text = "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted((repo / "prompts" / "harnesses").glob("*.md"))
    )

    for phrase in (
        "Keep global rules concise",
        "Use explicit file paths",
        "Prefer small reviewable batches",
        "Set sandbox and approval explicitly",
        "Keep permissions narrow",
        "Treat sandbox, container, browser, and IDE state as explicit context",
        "Do not hand-edit generated artifacts",
    ):
        assert phrase in core

    for phrase in (
        "Prefer small, reviewable edits",
        "Prefer explicit file lists",
        "Keep global rules concise and portable",
        "Keep global rules concise. Use repo-local",
        "Keep approval prompts meaningful",
        "Set sandbox and approval explicitly in automation",
        "Prefer explicit verification commands",
        "Prefer concise prompts with explicit file paths",
        "Keep tool permissions narrow",
        "Treat container, sandbox, and browser automation state",
        "Keep mode-specific rules aligned",
    ):
        assert phrase not in harness_text


def test_turn_state_marker_is_required_in_core():
    repo = Path(__file__).resolve().parents[1]
    core = (repo / "prompts" / "core.md").read_text(encoding="utf-8")

    assert "End any tool-using or work-producing turn with one state marker" in core
    for marker in ("`[done]`", "`[needs you]`", "`[waiting]`", "`[partial]`"):
        assert marker in core
    assert "One marker per turn, most-blocking wins" in core


def test_destructive_infra_commands_require_confirmation():
    repo = Path(__file__).resolve().parents[1]
    core = (repo / "prompts" / "core.md").read_text(encoding="utf-8")

    assert "Never run destructive infrastructure commands without explicit confirmation" in core
    assert "`terraform apply`" in core
    assert "`terraform destroy`" in core
    assert "`helm delete`" in core
    assert "`kubectl delete`" in core


def test_core_keeps_iac_checks_and_moves_personal_prefs_to_overlay():
    repo = Path(__file__).resolve().parents[1]
    core = (repo / "prompts" / "core.md").read_text(encoding="utf-8")
    example = (repo / "prompts" / "private.example.md").read_text(encoding="utf-8")

    assert "Prefer Bun over npm/yarn/pnpm" not in core
    assert "Prefer Bun over npm/yarn/pnpm" in example
    assert "Superpowers" not in core
    assert "consolidate-agents-md" not in core
    assert "`terraform plan`" in core
    assert "`ansible --check`" in core
    assert "`kubectl diff`" in core


def test_prompt_line_limits_are_enforced():
    repo = Path(__file__).resolve().parents[1]
    core_lines = (repo / "prompts" / "core.md").read_text(encoding="utf-8").splitlines()
    harness_paths = sorted((repo / "prompts" / "harnesses").glob("*.md"))

    assert len(core_lines) <= 100
    for path in harness_paths:
        assert len(path.read_text(encoding="utf-8").splitlines()) <= 20, path

    result = subprocess.run(
        ["python", "scripts/lint_prompts.py"],
        cwd=repo,
        check=False,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0
    assert "WARN: " not in result.stdout


def test_gitignore_covers_security_audit_and_tool_caches():
    repo = Path(__file__).resolve().parents[1]
    ignored = (repo / ".gitignore").read_text(encoding="utf-8").splitlines()

    for pattern in (
        "SECURITY-AUDIT.md",
        "/.codex",
        ".pytest_cache/",
        ".ruff_cache/",
        ".mypy_cache/",
        ".hypothesis/",
        ".tox/",
        ".nox/",
        ".coverage",
        "htmlcov/",
        "__pycache__/",
        "*.pyc",
    ):
        assert pattern in ignored

    assert "docs/superpowers/" in ignored
    assert "!docs/superpowers/specs/" not in ignored


def test_sync_ai_prompts_check_mode_validates_render_shape():
    repo = Path(__file__).resolve().parents[1]

    result = subprocess.run(
        ["scripts/sync-ai-prompts", "--check"],
        cwd=repo,
        check=False,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "Render shape check passed" in result.stdout


def test_sync_ai_prompts_dry_run_reports_manual_skips():
    repo = Path(__file__).resolve().parents[1]
    scrubbed_env = {
        key: value
        for key, value in os.environ.items()
        if key
        not in {
            "HERMES_AGENTS_PATH",
            "GENERIC_AGENTS_PATH",
            "ANTIGRAVITY_AGENTS_PATH",
        }
    }

    result = subprocess.run(
        ["scripts/sync-ai-prompts", "--dry-run"],
        cwd=repo,
        check=False,
        capture_output=True,
        text=True,
        env=scrubbed_env,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "skipping hermes: manual target requires HERMES_AGENTS_PATH" in result.stdout
    assert "skipping generic: manual target requires GENERIC_AGENTS_PATH" in result.stdout
    assert "would update claude:" in result.stdout
    assert "would update commandcode:" in result.stdout
    assert "would update antigravity:" in result.stdout


def test_backup_existing_preserves_multiple_backups_for_same_target(tmp_path):
    target = tmp_path / "AGENTS.md"
    backup_dir = tmp_path / "backups"

    target.write_text("first\n", encoding="utf-8")
    renderer.backup_existing(target, backup_dir)
    target.write_text("second\n", encoding="utf-8")
    renderer.backup_existing(target, backup_dir)

    backups = sorted(backup_dir.iterdir())
    assert len(backups) == 2
    assert {path.read_text(encoding="utf-8") for path in backups} == {"first\n", "second\n"}


def test_backup_existing_copies_dangling_symlink_without_crashing(tmp_path):
    target = tmp_path / "CLAUDE.md"
    target.symlink_to(tmp_path / "missing-AGENTS.md")
    backup_dir = tmp_path / "backups"

    renderer.backup_existing(target, backup_dir)

    backups = list(backup_dir.iterdir())
    assert len(backups) == 1
    assert backups[0].is_symlink()


def test_selected_harnesses_reject_empty_target_list():
    with pytest.raises(SystemExit, match="No harness names"):
        renderer.selected_harnesses([""])


def test_deploy_skips_manual_harness_without_override(tmp_path, capsys, monkeypatch):
    repo = Path(__file__).resolve().parents[1]
    monkeypatch.delenv("HERMES_AGENTS_PATH", raising=False)
    monkeypatch.delenv("NANOCLAW_AGENTS_PATH", raising=False)

    deployed = renderer.deploy(
        repo_root=repo,
        selected=["hermes"],
        stamp="2026-06-15",
        dry_run=True,
        backup_dir=tmp_path / "backups",
    )

    captured = capsys.readouterr()
    assert deployed == {}
    assert "skipping hermes: manual target requires HERMES_AGENTS_PATH" in captured.out


def test_deploy_allows_manual_harness_with_env_override(tmp_path, monkeypatch):
    repo = Path(__file__).resolve().parents[1]
    target = tmp_path / "HERMES.md"
    monkeypatch.setenv("HERMES_AGENTS_PATH", str(target))

    deployed = renderer.deploy(
        repo_root=repo,
        selected=["hermes"],
        stamp="2026-06-15",
        dry_run=False,
        backup_dir=tmp_path / "backups",
    )

    assert deployed == {"hermes": target}
    assert target.exists()
    assert "## Hermes Notes" in target.read_text(encoding="utf-8")


def test_deploy_refuses_colliding_targets_before_writing(tmp_path, monkeypatch):
    repo = Path(__file__).resolve().parents[1]
    target = tmp_path / "AGENTS.md"
    non_colliding_target = tmp_path / "claude" / "CLAUDE.md"
    monkeypatch.setenv("CODEX_AGENTS_PATH", str(target))
    monkeypatch.setenv("OPENCODE_AGENTS_PATH", str(target))
    monkeypatch.setenv("CLAUDE_AGENTS_PATH", str(non_colliding_target))

    with pytest.raises(SystemExit) as exc_info:
        renderer.deploy(
            repo_root=repo,
            selected=["codex,opencode,claude"],
            stamp="2026-06-15",
            dry_run=False,
            backup_dir=tmp_path / "backups",
        )

    message = str(exc_info.value)
    assert "Deploy target collision detected" in message
    assert "codex (OpenAI Codex)" in message
    assert "opencode (OpenCode)" in message
    assert str(target) in message
    assert not target.exists()
    assert not non_colliding_target.exists()


def test_deploy_refuses_normalized_colliding_targets_before_writing(tmp_path, monkeypatch):
    repo = Path(__file__).resolve().parents[1]
    (tmp_path / "alias").mkdir()
    alias_target = tmp_path / "alias" / ".." / "same" / "AGENTS.md"
    direct_target = tmp_path / "same" / "AGENTS.md"
    non_colliding_target = tmp_path / "claude" / "CLAUDE.md"
    monkeypatch.setenv("CODEX_AGENTS_PATH", str(alias_target))
    monkeypatch.setenv("OPENCODE_AGENTS_PATH", str(direct_target))
    monkeypatch.setenv("CLAUDE_AGENTS_PATH", str(non_colliding_target))

    with pytest.raises(SystemExit) as exc_info:
        renderer.deploy(
            repo_root=repo,
            selected=["codex,opencode,claude"],
            stamp="2026-06-15",
            dry_run=False,
            backup_dir=tmp_path / "backups",
        )

    message = str(exc_info.value)
    assert "Deploy target collision detected" in message
    assert "codex (OpenAI Codex)" in message
    assert "opencode (OpenCode)" in message
    assert str(direct_target.resolve(strict=False)) in message
    assert not direct_target.exists()
    assert not non_colliding_target.exists()


def test_render_document_uses_content_rev_without_stamp():
    one = renderer.render_document("## H\nfrag\n", "# C\ncore\n")
    two = renderer.render_document("## H\nfrag\n", "# C\ncore\n")
    three = renderer.render_document("## H\nfrag2\n", "# C\ncore\n")

    assert one == two
    assert "rev " in one.split("-->")[0]
    assert one != three


def test_enforce_budget_rejects_oversized_render():
    unbounded = renderer.Harness("x", "X", "x.md", "X.md", None, "X_PATH")
    renderer.enforce_budget(unbounded, "small")
    bounded = renderer.Harness("x", "X", "x.md", "X.md", None, "X_PATH", max_bytes=3)
    with pytest.raises(SystemExit, match="budget"):
        renderer.enforce_budget(bounded, "abcdef")


def test_deploy_refuses_symlink_destination(tmp_path, monkeypatch):
    repo = Path(__file__).resolve().parents[1]
    target = tmp_path / "outside.md"
    target.write_text("keep\n", encoding="utf-8")
    link = tmp_path / "AGENTS.md"
    link.symlink_to(target)
    monkeypatch.setenv("CODEX_AGENTS_PATH", str(link))

    with pytest.raises(SystemExit, match="symlink"):
        renderer.deploy(
            repo, selected=["codex"], stamp="2026-06-15", dry_run=False, backup_dir=tmp_path / "b"
        )

    assert target.read_text(encoding="utf-8") == "keep\n"


def test_cli_deploy_requires_target():
    repo = Path(__file__).resolve().parents[1]
    result = subprocess.run(
        ["scripts/sync-ai-prompts", "--deploy"], cwd=repo, capture_output=True, text=True, check=False
    )

    assert result.returncode != 0
    assert "--deploy requires --target" in result.stdout + result.stderr


def test_status_reports_drift_then_in_sync(tmp_path, monkeypatch, capsys):
    repo = Path(__file__).resolve().parents[1]
    target = tmp_path / "CLAUDE.md"
    monkeypatch.setenv("CLAUDE_AGENTS_PATH", str(target))

    assert renderer.status(repo, ["claude"], "2026-06-15") == 1
    capsys.readouterr()

    renderer.deploy(repo, selected=["claude"], stamp="2026-06-15", dry_run=False, backup_dir=tmp_path / "b")
    capsys.readouterr()

    assert renderer.status(repo, ["claude"], "2026-06-15") == 0
    assert "in sync" in capsys.readouterr().out


def test_target_path_prefers_explicit_override_then_native_env(tmp_path):
    assert renderer.target_path("codex", home=tmp_path, env={"CODEX_HOME": "/native"}) == Path("/native/AGENTS.md")
    assert renderer.target_path(
        "codex",
        home=tmp_path,
        env={"CODEX_HOME": "/native", "CODEX_AGENTS_PATH": "/explicit/AGENTS.md"},
    ) == Path("/explicit/AGENTS.md")
    assert renderer.target_path("opencode", home=tmp_path, env={"OPENCODE_CONFIG_DIR": "/oc"}) == Path("/oc/AGENTS.md")
    assert renderer.target_path("claude", home=tmp_path, env={"CLAUDE_CONFIG_DIR": "/cc"}) == Path("/cc/CLAUDE.md")


def test_gitattributes_pins_lf_line_endings():
    repo = Path(__file__).resolve().parents[1]
    attrs = (repo / ".gitattributes").read_text(encoding="utf-8")

    assert "text=auto eol=lf" in attrs


def test_backup_existing_flattens_windows_style_paths(tmp_path):
    backup_dir = tmp_path / "backups"
    weird = tmp_path / "C:" / "Users" / "me" / "AGENTS.md"
    weird.parent.mkdir(parents=True)
    weird.write_text("x\n", encoding="utf-8")

    renderer.backup_existing(weird, backup_dir)

    backups = list(backup_dir.iterdir())
    assert len(backups) == 1
    assert ":" not in backups[0].name
    assert "\\" not in backups[0].name


def test_prune_backups_keeps_newest(tmp_path):
    backup_dir = tmp_path / "b"
    backup_dir.mkdir()
    for index in range(5):
        path = backup_dir / f"x-{index}.bak"
        path.write_text(str(index), encoding="utf-8")
        os.utime(path, (1000 + index, 1000 + index))

    assert renderer.prune_backups(backup_dir, 2, dry_run=True) == 0
    assert len(list(backup_dir.iterdir())) == 5

    assert renderer.prune_backups(backup_dir, 2, dry_run=False) == 0
    assert sorted(path.name for path in backup_dir.iterdir()) == ["x-3.bak", "x-4.bak"]
