import importlib.util
import os
import shutil
import subprocess
from pathlib import Path


def load_renderer():
    module_path = Path(__file__).resolve().parents[1] / "scripts" / "render_prompts.py"
    spec = importlib.util.spec_from_file_location("render_prompts", module_path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def test_render_document_places_harness_fragment_before_core():
    renderer = load_renderer()

    rendered = renderer.render_document(
        harness="codex",
        fragment="## Codex\ncodex body\n",
        core="# Global\ncore body\n",
        stamp="2026-04-25",
    )

    assert rendered.startswith("<!-- Generated by sync-ai-prompts on 2026-04-25.")
    assert rendered.index("codex body") < rendered.index("core body")
    assert "Edit prompts/core.md and prompts/harnesses/*.md" in rendered
    assert "/home/id" not in rendered


def test_render_document_places_private_overlay_after_core():
    renderer = load_renderer()

    rendered = renderer.render_document(
        harness="claude",
        fragment="## Claude\nclaude body\n",
        core="# Global\ncore body\n",
        private="## Private\nprivate body\n",
        stamp="2026-04-25",
    )

    assert rendered.index("claude body") < rendered.index("core body")
    assert rendered.index("core body") < rendered.index("private body")
    assert "private.example.md" in rendered


def test_harness_catalog_expands_beyond_claude_codex_opencode():
    renderer = load_renderer()

    harnesses = set(renderer.harness_names())

    assert {"claude", "codex", "opencode"}.issubset(harnesses)
    assert {
        "gemini",
        "cursor",
        "windsurf",
        "copilot",
        "aider",
        "goose",
        "amp",
        "continue",
        "cline",
        "roo",
        "qwen",
        "warp",
        "kiro",
        "augment",
        "openhands",
    }.issubset(harnesses)


def test_target_path_uses_home_and_env_override(tmp_path):
    renderer = load_renderer()

    default_path = renderer.target_path("codex", home=tmp_path, env={})
    override_path = renderer.target_path(
        "codex",
        home=tmp_path,
        env={"CODEX_AGENTS_PATH": "/custom/AGENTS.md"},
    )

    assert default_path == tmp_path / "AGENTS.md"
    assert override_path == Path("/custom/AGENTS.md")


def test_render_all_writes_selected_harnesses_to_output_dir(tmp_path):
    renderer = load_renderer()
    repo = tmp_path / "repo"
    (repo / "prompts" / "harnesses").mkdir(parents=True)
    (repo / "prompts" / "core.md").write_text("# Core\nshared\n", encoding="utf-8")
    (repo / "prompts" / "private.md").write_text("## Private\nlocal only\n", encoding="utf-8")
    (repo / "prompts" / "harnesses" / "claude.md").write_text(
        "## Claude\nclaude only\n",
        encoding="utf-8",
    )
    (repo / "prompts" / "harnesses" / "codex.md").write_text(
        "## Codex\ncodex only\n",
        encoding="utf-8",
    )

    written = renderer.render_all(
        repo_root=repo,
        out_dir=tmp_path / "out",
        selected=["claude", "codex"],
        stamp="2026-04-25",
    )

    assert written == {
        "claude": tmp_path / "out" / "CLAUDE.md",
        "codex": tmp_path / "out" / "AGENTS.md",
    }
    assert "claude only" in written["claude"].read_text(encoding="utf-8")
    assert "shared" in written["codex"].read_text(encoding="utf-8")
    assert "local only" in written["codex"].read_text(encoding="utf-8")


def test_common_guidance_lives_in_core_not_harness_fragments():
    repo = Path(__file__).resolve().parents[1]
    core = (repo / "prompts" / "core.md").read_text(encoding="utf-8")
    harness_text = "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted((repo / "prompts" / "harnesses").glob("*.md"))
    )

    for phrase in (
        "versions, features, pricing, APIs, docs",
        "Functional status markers are fine",
        "Use dense bullet lists",
        "environment scrubbing can hide",
    ):
        assert phrase in core

    for phrase in (
        "Search the web first for versions",
        "Verify versions, features, pricing, and docs first",
        "Functional status markers are allowed",
        "Prefer dense bullet lists",
        "If subprocess environment scrubbing is enabled",
    ):
        assert phrase not in harness_text


def test_vendor_harnesses_define_model_ladders():
    repo = Path(__file__).resolve().parents[1]

    claude = (repo / "prompts" / "harnesses" / "claude.md").read_text(encoding="utf-8")
    codex = (repo / "prompts" / "harnesses" / "codex.md").read_text(encoding="utf-8")
    gemini = (repo / "prompts" / "harnesses" / "gemini.md").read_text(encoding="utf-8")

    assert "Haiku = lower cost/fast" in claude
    assert "Sonnet = default balanced" in claude
    assert "Opus = highest capability" in claude
    assert "mini/smaller GPT = lower cost/fast" in codex
    assert "current GPT = default high-capability" in codex
    assert "do not freeze stale names" in codex
    assert "Flash-Lite = lower cost/high throughput" in gemini
    assert "Flash = balanced speed and capability" in gemini
    assert "Pro = strongest reasoning" in gemini


def test_effort_guidance_is_general_with_vendor_caveats():
    repo = Path(__file__).resolve().parents[1]

    core = (repo / "prompts" / "core.md").read_text(encoding="utf-8")
    claude = (repo / "prompts" / "harnesses" / "claude.md").read_text(encoding="utf-8")
    codex = (repo / "prompts" / "harnesses" / "codex.md").read_text(encoding="utf-8")
    gemini = (repo / "prompts" / "harnesses" / "gemini.md").read_text(encoding="utf-8")

    assert "Reasoning or effort levels are vendor-specific" in core
    assert "Opus 4.7 adds `xhigh`" in claude
    assert "Codex/OpenAI reasoning effort names" in codex
    assert "Gemini exposes thinking controls differently" in gemini


def test_generic_workflow_guidance_stays_in_core():
    repo = Path(__file__).resolve().parents[1]
    core = (repo / "prompts" / "core.md").read_text(encoding="utf-8")
    harness_text = "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted((repo / "prompts" / "harnesses").glob("*.md"))
    )

    for phrase in (
        "Keep global rules concise",
        "Use explicit file paths",
        "Prefer small reviewable batches",
        "Set sandbox and approval explicitly",
        "Keep permissions narrow",
        "Treat sandbox, container, browser, and IDE state as explicit context",
    ):
        assert phrase in core

    for phrase in (
        "Prefer small, reviewable edits",
        "Prefer explicit file lists",
        "Keep global rules concise and portable",
        "Keep global rules concise. Use repo-local",
        "Keep approval prompts meaningful",
        "Set sandbox and approval explicitly in automation",
        "Prefer explicit verification commands",
        "Prefer concise prompts with explicit file paths",
        "Keep tool permissions narrow",
        "Treat container, sandbox, and browser automation state",
        "Keep mode-specific rules aligned",
    ):
        assert phrase not in harness_text


def test_destructive_infra_commands_require_confirmation():
    repo = Path(__file__).resolve().parents[1]
    core = (repo / "prompts" / "core.md").read_text(encoding="utf-8")

    assert "Never run destructive infrastructure commands without explicit confirmation" in core
    assert "`terraform apply`" in core
    assert "`terraform destroy`" in core
    assert "`helm delete`" in core
    assert "`kubectl delete`" in core


def test_core_keeps_iac_and_bun_preferences():
    repo = Path(__file__).resolve().parents[1]
    core = (repo / "prompts" / "core.md").read_text(encoding="utf-8")

    assert "Prefer Bun over npm/yarn/pnpm" in core
    assert "`terraform plan`" in core
    assert "`ansible --check`" in core
    assert "`kubectl diff`" in core


def test_prompt_line_limits_are_enforced():
    repo = Path(__file__).resolve().parents[1]
    core_lines = (repo / "prompts" / "core.md").read_text(encoding="utf-8").splitlines()
    harness_paths = sorted((repo / "prompts" / "harnesses").glob("*.md"))

    assert len(core_lines) <= 100
    for path in harness_paths:
        assert len(path.read_text(encoding="utf-8").splitlines()) <= 10, path

    result = subprocess.run(
        ["python", "scripts/lint_prompts.py"],
        cwd=repo,
        check=False,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0
    assert "WARN: " in result.stdout


def test_gitignore_covers_security_audit_and_tool_caches():
    repo = Path(__file__).resolve().parents[1]
    ignored = (repo / ".gitignore").read_text(encoding="utf-8").splitlines()

    for pattern in (
        "SECURITY-AUDIT.md",
        ".pytest_cache/",
        ".ruff_cache/",
        ".mypy_cache/",
        ".hypothesis/",
        ".tox/",
        ".nox/",
        ".coverage",
        "htmlcov/",
        "__pycache__/",
        "*.pyc",
    ):
        assert pattern in ignored


def test_backup_existing_preserves_multiple_backups_for_same_target(tmp_path):
    renderer = load_renderer()
    target = tmp_path / "AGENTS.md"
    backup_dir = tmp_path / "backups"

    target.write_text("first\n", encoding="utf-8")
    renderer.backup_existing(target, backup_dir)
    target.write_text("second\n", encoding="utf-8")
    renderer.backup_existing(target, backup_dir)

    backups = sorted(backup_dir.iterdir())
    assert len(backups) == 2
    assert {path.read_text(encoding="utf-8") for path in backups} == {"first\n", "second\n"}


def prepare_autoimprove_repo(tmp_path):
    source = Path(__file__).resolve().parents[1]
    repo = tmp_path / "repo"
    shutil.copytree(source / "scripts", repo / "scripts")
    shutil.copytree(source / "prompts", repo / "prompts", ignore=shutil.ignore_patterns("private.md"))
    (repo / "tests").mkdir()
    (repo / "tests" / "test_smoke.py").write_text("def test_smoke():\n    assert True\n", encoding="utf-8")

    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.email", "test@example.invalid"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "Test User"], cwd=repo, check=True)
    subprocess.run(["git", "add", "."], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-qm", "initial"], cwd=repo, check=True)
    return repo


def test_autoimprove_rejects_unknown_mode(tmp_path):
    repo = prepare_autoimprove_repo(tmp_path)

    result = subprocess.run(
        ["bash", "scripts/autoimprove-prompts", "--mode", "bogus", "--iterations", "0"],
        cwd=repo,
        check=False,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 2
    assert "Unsupported mode: bogus" in result.stderr


def test_autoimprove_detects_untracked_agent_output(tmp_path):
    repo = prepare_autoimprove_repo(tmp_path)
    fake_bin = tmp_path / "bin"
    fake_bin.mkdir()
    fake_claude = fake_bin / "claude"
    fake_claude.write_text(
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        "printf 'new doc\\n' > AGENT_OUTPUT.md\n",
        encoding="utf-8",
    )
    fake_claude.chmod(0o755)
    env = {
        **os.environ,
        "PATH": f"{fake_bin}:{os.environ['PATH']}",
        "AGENTS_AUTOIMPROVE_HARNESS": "claude",
    }

    result = subprocess.run(
        ["bash", "scripts/autoimprove-prompts", "--iterations", "1", "--mode", "step"],
        cwd=repo,
        env=env,
        check=False,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stderr
    assert "Verified improvement candidate" in result.stdout
    assert "AGENT_OUTPUT.md" in result.stdout
