#!/usr/bin/env python3
"""Render subagent definitions from agents/*.md into harness-native files.

One source per agent, flat frontmatter, prompt body. The renderer resolves
model tier and effort per harness, maps abstract tool names, injects the hard
invariants, and writes build/agents/<harness>/. Deploy is explicit.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import tomllib
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from tempfile import TemporaryDirectory

from render_invariants import read_invariants
from render_prompts import backup_existing


TIERS = ("cheap", "mid", "flagship", "apex")
EFFORTS = ("low", "medium", "high", "xhigh")
TOOLS = ("read", "search", "edit", "write", "shell", "shell-ro", "web")
WRITE_TOOLS = frozenset({"edit", "write", "shell"})
REQUIRED_KEYS = ("name", "description", "tier", "effort", "tools")
OPTIONAL_KEYS = ("max_turns",)
NAME_RE = re.compile(r"^[a-z][a-z0-9-]*$")
MODEL_RE = re.compile(r"^[A-Za-z0-9._:/+-]+$")
KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_-]*$")

AGENT_HARNESSES = ("claude", "codex", "opencode", "commandcode")
# Command Code silently ignores custom files that reuse a built-in name.
RESERVED_NAMES = {"commandcode": frozenset({"explore", "plan", "review", "general"})}
# These harnesses let a custom agent shadow a built-in; allowed, but noticed.
SHADOWED_NAMES = {
    "codex": frozenset({"default", "worker", "explorer"}),
    "opencode": frozenset({"general", "explore", "scout"}),
}

GENERATED_MARKER = "Generated by render-agents"


@dataclass(frozen=True)
class AgentSpec:
    name: str
    description: str
    tier: str
    effort: str
    tools: tuple[str, ...]
    max_turns: int | None
    body: str
    source: Path
    source_text: str


def parse_frontmatter(text: str, source: Path) -> tuple[dict[str, str], str]:
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        raise SystemExit(f"{source}: missing opening frontmatter delimiter")
    fields: dict[str, str] = {}
    for index in range(1, len(lines)):
        line = lines[index]
        if line.strip() == "---":
            return fields, "".join(lines[index + 1 :])
        if not line.strip():
            continue
        if ":" not in line:
            raise SystemExit(f"{source}: frontmatter line without a colon: {line.strip()}")
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            quote = value[0]
            interior = value[1:-1]
            if quote not in interior:
                value = interior
        if key in fields:
            raise SystemExit(f"{source}: duplicate frontmatter key: {key}")
        fields[key] = value
    raise SystemExit(f"{source}: missing closing frontmatter delimiter")


def parse_tools(raw: str, source: Path) -> tuple[str, ...]:
    tools: list[str] = []
    for item in raw.split(","):
        tool = item.strip()
        if not tool:
            continue
        if tool not in TOOLS:
            raise SystemExit(f"{source}: unknown tool '{tool}'; allowed: {', '.join(TOOLS)}")
        if tool not in tools:
            tools.append(tool)
    if not tools:
        raise SystemExit(f"{source}: tools must name at least one tool")
    if "shell" in tools and "shell-ro" in tools:
        raise SystemExit(f"{source}: tools cannot combine shell and shell-ro")
    return tuple(tools)


def load_agent(path: Path) -> AgentSpec:
    text = path.read_text(encoding="utf-8")
    fields, body = parse_frontmatter(text, path)
    for key in REQUIRED_KEYS:
        if key not in fields:
            raise SystemExit(f"{path}: missing key '{key}'")
    for key in fields:
        if key not in REQUIRED_KEYS and key not in OPTIONAL_KEYS:
            raise SystemExit(f"{path}: unknown key '{key}'")

    name = fields["name"]
    if not NAME_RE.match(name):
        raise SystemExit(f"{path}: name '{name}' must match {NAME_RE.pattern}")
    if name != path.stem:
        raise SystemExit(f"{path}: name '{name}' does not match filename stem '{path.stem}'")
    for harness, reserved in RESERVED_NAMES.items():
        if name in reserved:
            raise SystemExit(f"{path}: name '{name}' is reserved by {harness}")

    tier = fields["tier"]
    if tier not in TIERS:
        raise SystemExit(f"{path}: unknown tier '{tier}'; allowed: {', '.join(TIERS)}")
    effort = fields["effort"]
    if effort not in EFFORTS:
        raise SystemExit(f"{path}: unknown effort '{effort}'; allowed: {', '.join(EFFORTS)}")
    description = fields["description"]
    if not description:
        raise SystemExit(f"{path}: description must be one non-empty line")
    if any(ord(char) < 32 for char in description):
        raise SystemExit(f"{path}: description contains a control character")

    max_turns: int | None = None
    if "max_turns" in fields:
        if not fields["max_turns"].isdigit() or int(fields["max_turns"]) < 1:
            raise SystemExit(f"{path}: max_turns must be a positive integer")
        max_turns = int(fields["max_turns"])

    if not body.strip():
        raise SystemExit(f"{path}: empty prompt body")

    return AgentSpec(
        name=name,
        description=description,
        tier=tier,
        effort=effort,
        tools=parse_tools(fields["tools"], path),
        max_turns=max_turns,
        body=body.strip() + "\n",
        source=path,
        source_text=text,
    )


def load_agents(repo_root: Path) -> list[AgentSpec]:
    agents_dir = repo_root / "agents"
    if not agents_dir.is_dir():
        raise SystemExit(f"Missing agents directory: {agents_dir}")
    specs = [load_agent(path) for path in sorted(agents_dir.glob("*.md"))]
    if not specs:
        raise SystemExit(f"No agent sources found in {agents_dir}")
    return specs


DEFAULT_MODELS: dict[str, dict[str, str | None]] = {
    "claude": {"cheap": "haiku", "mid": "sonnet", "flagship": "opus", "apex": "fable"},
    "codex": {"cheap": "gpt-5.6-luna", "mid": "gpt-5.6-terra", "flagship": "gpt-5.6-sol", "apex": None},
    # No generic aliases; commonly self-hosted or routed. Inherit the session model
    # unless prompts/models.local.json names provider/model IDs.
    "opencode": {tier: None for tier in TIERS},
    "commandcode": {tier: None for tier in TIERS},
}
DEFAULT_EFFORT_KEYS = {
    "claude": "effort",
    "codex": "model_reasoning_effort",
    "opencode": "reasoningEffort",
    "commandcode": "reasoningEffort",
}
OVERRIDE_KEYS = frozenset({"tiers", "agents", "effort_key"})
AGENT_OVERRIDE_KEYS = frozenset({"tier", "effort"})


@dataclass(frozen=True)
class Resolved:
    model: str | None
    effort: str
    effort_key: str
    notices: list[str]


def validate_overrides(data: object, source: Path) -> dict:
    label = f"{source}"
    if not isinstance(data, dict):
        raise SystemExit(f"{label}: root must be an object")
    for harness, entry in data.items():
        if harness not in AGENT_HARNESSES:
            raise SystemExit(f"{label}: unknown harness '{harness}'")
        if not isinstance(entry, dict):
            raise SystemExit(f"{label}: '{harness}' must be an object")
        for key in entry:
            if key not in OVERRIDE_KEYS:
                raise SystemExit(f"{label}: '{harness}.{key}' is not one of {sorted(OVERRIDE_KEYS)}")
        tiers = entry.get("tiers", {})
        if not isinstance(tiers, dict):
            raise SystemExit(f"{label}: '{harness}.tiers' must be an object")
        for tier, model in tiers.items():
            if tier not in TIERS:
                raise SystemExit(f"{label}: '{harness}.tiers.{tier}' is not a tier")
            if not isinstance(model, str) or not model:
                raise SystemExit(f"{label}: '{harness}.tiers.{tier}' must be a non-empty string")
            if not MODEL_RE.match(model):
                raise SystemExit(
                    f"{label}: '{harness}.tiers.{tier}' has characters outside {MODEL_RE.pattern}"
                )
        agents = entry.get("agents", {})
        if not isinstance(agents, dict):
            raise SystemExit(f"{label}: '{harness}.agents' must be an object")
        for name, fields in agents.items():
            if not isinstance(fields, dict):
                raise SystemExit(f"{label}: '{harness}.agents.{name}' must be an object")
            for key, value in fields.items():
                if key not in AGENT_OVERRIDE_KEYS:
                    raise SystemExit(f"{label}: '{harness}.agents.{name}.{key}' is not tier or effort")
                allowed = TIERS if key == "tier" else EFFORTS
                if value not in allowed:
                    raise SystemExit(f"{label}: '{harness}.agents.{name}.{key}' = '{value}' is invalid")
        effort_key = entry.get("effort_key")
        if effort_key is not None and (not isinstance(effort_key, str) or not KEY_RE.match(effort_key)):
            raise SystemExit(f"{label}: '{harness}.effort_key' must match {KEY_RE.pattern}")
    return data


def load_overrides(repo_root: Path) -> dict:
    path = repo_root / "prompts" / "models.local.json"
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(f"{path}: invalid JSON: {exc}")
    return validate_overrides(data, path)


def resolve(spec: AgentSpec, harness: str, overrides: dict) -> Resolved:
    entry = overrides.get(harness, {})
    per_agent = entry.get("agents", {}).get(spec.name, {})
    tier = per_agent.get("tier", spec.tier)
    effort = per_agent.get("effort", spec.effort)
    models = dict(DEFAULT_MODELS[harness])
    models.update(entry.get("tiers", {}))
    effort_key = entry.get("effort_key", DEFAULT_EFFORT_KEYS[harness])

    notices: list[str] = []
    model = models[tier]
    if tier == "apex" and model is None and models["flagship"] is not None:
        model = models["flagship"]
        notices.append(f"{harness}/{spec.name}: no apex model configured; using flagship '{model}'")
    if spec.name in SHADOWED_NAMES.get(harness, frozenset()):
        notices.append(f"{harness}/{spec.name}: shadows the built-in agent of the same name")
    return Resolved(model=model, effort=effort, effort_key=effort_key, notices=notices)


CLAUDE_TOOLS = {
    "read": ("Read",),
    "search": ("Grep", "Glob"),
    "edit": ("Edit",),
    "write": ("Write",),
    "shell": ("Bash",),
    "shell-ro": ("Bash",),
    "web": ("WebFetch", "WebSearch"),
}
COMMANDCODE_TOOLS = {
    "read": ("read_file", "read_directory"),
    "search": ("grep", "glob"),
    "edit": ("edit_file",),
    "write": ("write_file",),
    "shell": ("shell_command", "run_command"),
    "shell-ro": ("shell_command",),
    "web": ("web_fetch", "web_search"),
}
OPENCODE_TOOLS = {
    "read": ("read", "list"),
    "search": ("grep", "glob"),
    "edit": ("edit",),
    "write": ("edit",),
    "shell": ("bash",),
    "shell-ro": ("bash",),
    "web": ("webfetch", "websearch"),
}
OPENCODE_KNOWN = ("read", "list", "grep", "glob", "edit", "bash", "webfetch", "websearch", "task")
OPENCODE_RO_BASH = ("git diff*", "git log*", "git status*", "git show*", "git blame*", "ls*", "cat*", "head*", "sed -n*", "rg*", "grep*", "find*")


def expand_tools(tools: tuple[str, ...], table: dict[str, tuple[str, ...]]) -> list[str]:
    names: list[str] = []
    for tool in tools:
        for name in table[tool]:
            if name not in names:
                names.append(name)
    return names


def generated_header(spec: AgentSpec, invariants: str) -> str:
    digest = hashlib.sha256((invariants + "\n" + spec.source_text).encode("utf-8")).hexdigest()[:12]
    return (
        f"{GENERATED_MARKER} from agents/{spec.name}.md (hash {digest}). "
        "Edit the source and rerun scripts/render-agents; do not edit this file."
    )


def yaml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def markdown_body(spec: AgentSpec, invariants: str) -> str:
    return f"<!-- {generated_header(spec, invariants)} -->\n\n{invariants.rstrip()}\n\n{spec.body}"


def render_claude(spec: AgentSpec, resolved: Resolved, invariants: str) -> str:
    lines = [
        "---",
        f"name: {spec.name}",
        f"description: {yaml_string(spec.description)}",
        f"tools: {', '.join(expand_tools(spec.tools, CLAUDE_TOOLS))}",
    ]
    if resolved.model is not None:
        lines.append(f"model: {yaml_string(resolved.model)}")
    lines.append(f"{resolved.effort_key}: {resolved.effort}")
    if spec.max_turns is not None:
        lines.append(f"maxTurns: {spec.max_turns}")
    lines.append("---")
    return "\n".join(lines) + "\n" + markdown_body(spec, invariants)


def toml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_codex(spec: AgentSpec, resolved: Resolved, invariants: str) -> str:
    instructions = f"{invariants.rstrip()}\n\n{spec.body}"
    if '"""' in instructions:
        raise SystemExit(f"{spec.source}: body contains a TOML triple quote (\"\"\"); cannot render for codex")
    sandbox = "workspace-write" if WRITE_TOOLS & set(spec.tools) else "read-only"
    lines = [
        f"# {generated_header(spec, invariants)}",
        f"name = {toml_string(spec.name)}",
        f"description = {toml_string(spec.description)}",
    ]
    if resolved.model is not None:
        lines.append(f"model = {toml_string(resolved.model)}")
    lines.append(f"{resolved.effort_key} = {toml_string(resolved.effort)}")
    lines.append(f"sandbox_mode = {toml_string(sandbox)}")
    # fork_turns is a spawn_agent parameter, not a role-file key; Codex rejects
    # the whole file as malformed if it appears here. The harness fragment tells
    # the parent to pass agent_type and fork_turns="none" at spawn time.
    lines.append('developer_instructions = """')
    lines.append(instructions.replace("\\", "\\\\").rstrip())
    lines.append('"""')
    text = "\n".join(lines) + "\n"
    try:
        tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        raise SystemExit(f"{spec.source}: rendered codex TOML is invalid: {exc}")
    return text


def render_opencode(spec: AgentSpec, resolved: Resolved, invariants: str) -> str:
    allowed = set(expand_tools(spec.tools, OPENCODE_TOOLS))
    lines = [
        "---",
        f"description: {yaml_string(spec.description)}",
        "mode: subagent",
    ]
    if resolved.model is not None:
        lines.append(f"model: {yaml_string(resolved.model)}")
    lines.append(f"{resolved.effort_key}: {resolved.effort}")
    if spec.max_turns is not None:
        lines.append(f"steps: {spec.max_turns}")
    lines.append("permission:")
    for tool in OPENCODE_KNOWN:
        if tool == "task":
            lines.append("  task: deny")
        elif tool == "bash" and "shell-ro" in spec.tools:
            lines.append("  bash:")
            lines.append('    "*": deny')
            lines.extend(f"    {yaml_string(pattern)}: allow" for pattern in OPENCODE_RO_BASH)
        else:
            lines.append(f"  {tool}: {'allow' if tool in allowed else 'deny'}")
    lines.append("---")
    return "\n".join(lines) + "\n" + markdown_body(spec, invariants)


def render_commandcode(spec: AgentSpec, resolved: Resolved, invariants: str) -> str:
    lines = [
        "---",
        f"name: {spec.name}",
        f"description: {yaml_string(spec.description)}",
        f"tools: {', '.join(expand_tools(spec.tools, COMMANDCODE_TOOLS))}",
    ]
    if resolved.model is not None:
        lines.append(f"model: {yaml_string(resolved.model)}")
    lines.append(f"{resolved.effort_key}: {resolved.effort}")
    if spec.max_turns is not None:
        lines.append(f"maxTurns: {spec.max_turns}")
    lines.append("---")
    return "\n".join(lines) + "\n" + markdown_body(spec, invariants)


RENDERERS = {
    "claude": render_claude,
    "codex": render_codex,
    "opencode": render_opencode,
    "commandcode": render_commandcode,
}
EXTENSIONS = {"claude": ".md", "codex": ".toml", "opencode": ".md", "commandcode": ".md"}


TARGET_DIRS = {
    "claude": ("{home}/.claude/agents", "CLAUDE_AGENTS_DIR"),
    "codex": ("{home}/.codex/agents", "CODEX_AGENTS_DIR"),
    "opencode": ("{home}/.config/opencode/agents", "OPENCODE_AGENTS_DIR"),
    "commandcode": ("{home}/.commandcode/agents", "COMMANDCODE_AGENTS_DIR"),
}
HARNESS_DISPLAY = {
    "claude": "Claude Code",
    "codex": "OpenAI Codex",
    "opencode": "OpenCode",
    "commandcode": "Command Code",
}


def selected_agent_harnesses(selected: list[str] | None) -> list[str]:
    if not selected:
        return list(AGENT_HARNESSES)
    names: list[str] = []
    for item in selected:
        names.extend(part.strip() for part in item.split(",") if part.strip())
    if not names:
        raise SystemExit("No harness names parsed from --target; nothing to do")
    for name in names:
        if name not in AGENT_HARNESSES:
            raise SystemExit(f"Unknown agent harness: {name}. Supported: {', '.join(AGENT_HARNESSES)}")
    return names


def agent_target_dir(harness: str, home: Path | None = None, env: dict[str, str] | None = None) -> Path:
    template, env_var = TARGET_DIRS[harness]
    values = os.environ if env is None else env
    if values.get(env_var):
        return Path(values[env_var]).expanduser()
    home_path = Path.home() if home is None else Path(home)
    return Path(template.format(home=home_path)).expanduser()


def render_harness(
    specs: list[AgentSpec], harness: str, overrides: dict, invariants: str
) -> tuple[dict[str, str], list[str]]:
    rendered: dict[str, str] = {}
    notices: list[str] = []
    models: list[str | None] = []
    for spec in specs:
        resolved = resolve(spec, harness, overrides)
        notices.extend(resolved.notices)
        models.append(resolved.model)
        rendered[spec.name + EXTENSIONS[harness]] = RENDERERS[harness](spec, resolved, invariants)
    if all(model is None for model in models):
        notices.append(f"{harness}: every tier renders as inherit; set prompts/models.local.json to enable tiering")
    return rendered, notices


def print_notices(notices: list[str]) -> None:
    for notice in dict.fromkeys(notices):
        print(f"notice: {notice}")


def render_all(
    repo_root: Path, out_dir: Path, selected: list[str] | None, overrides: dict
) -> dict[str, list[Path]]:
    specs = load_agents(repo_root)
    invariants = read_invariants(repo_root)
    written: dict[str, list[Path]] = {}
    notices: list[str] = []
    for harness in selected_agent_harnesses(selected):
        files, harness_notices = render_harness(specs, harness, overrides, invariants)
        notices.extend(harness_notices)
        dest_dir = out_dir / harness
        dest_dir.mkdir(parents=True, exist_ok=True)
        paths: list[Path] = []
        for filename, text in files.items():
            dest = dest_dir / filename
            dest.write_text(text, encoding="utf-8")
            paths.append(dest)
        written[harness] = paths
    print_notices(notices)
    return written


def check(repo_root: Path, selected: list[str] | None) -> int:
    # Honors the gitignored local override file, so local and CI renders can
    # differ by design.
    overrides = load_overrides(repo_root)
    with TemporaryDirectory() as temp_dir:
        written = render_all(repo_root, Path(temp_dir), selected, overrides)
        for harness, paths in written.items():
            for path in paths:
                text = path.read_text(encoding="utf-8")
                if GENERATED_MARKER not in text:
                    print(f"ERROR: {harness}/{path.name} lacks the generated marker")
                    return 1
                if harness == "codex":
                    tomllib.loads(text)
                else:
                    parse_frontmatter(text, path)
    print("Agent render check passed")
    return 0


def read_text_or_none(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None


def is_generated(path: Path) -> bool:
    text = read_text_or_none(path)
    return text is not None and GENERATED_MARKER in text


def deploy(
    repo_root: Path, selected: list[str] | None, overrides: dict, dry_run: bool, backup_dir: Path
) -> None:
    specs = load_agents(repo_root)
    invariants = read_invariants(repo_root)
    notices: list[str] = []
    for harness in selected_agent_harnesses(selected):
        files, harness_notices = render_harness(specs, harness, overrides, invariants)
        notices.extend(harness_notices)
        target = agent_target_dir(harness)
        extension = EXTENSIONS[harness]

        stale = []
        if target.is_dir():
            stale = [
                path
                for path in sorted(target.glob(f"*{extension}"))
                if path.name not in files and is_generated(path)
            ]

        if dry_run:
            for filename in files:
                print(f"would write {harness}: {target / filename}")
            for path in stale:
                print(f"would remove stale {harness}: {path}")
            continue

        target.mkdir(parents=True, exist_ok=True)
        # Refuse before the first write so a bad entry cannot leave the
        # directory half-updated.
        for filename in files:
            dest = target / filename
            if dest.exists() and not dest.is_file():
                raise SystemExit(f"{dest} exists and is not a regular file; move it aside")
        for filename, text in files.items():
            dest = target / filename
            if read_text_or_none(dest) == text:
                print(f"unchanged {harness}: {dest}")
                continue
            backup_existing(dest, backup_dir)
            dest.write_text(text, encoding="utf-8")
            print(f"updated {harness}: {dest}")
        for path in stale:
            backup_existing(path, backup_dir)
            path.unlink()
            print(f"removed stale {harness}: {path} (backup in {backup_dir})")
    print_notices(notices)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description="Render and deploy subagent definitions.")
    parser.add_argument("--repo-root", type=Path, default=repo_root)
    parser.add_argument("--out-dir", type=Path, default=repo_root / "build" / "agents")
    parser.add_argument("--target", action="append", help="Harness target, repeatable or comma-separated.")
    parser.add_argument("--deploy", action="store_true", help="Write rendered agents to global harness directories.")
    parser.add_argument("--dry-run", action="store_true", help="Print deploy actions without writing.")
    parser.add_argument("--check", action="store_true", help="Validate rendered output without persistent writes.")
    parser.add_argument("--list-targets", action="store_true", help="List supported harnesses and target directories.")
    parser.add_argument("--backup-dir", type=Path, default=repo_root / ".backups", help="Directory for deploy backups.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if args.list_targets:
        for harness in selected_agent_harnesses(args.target):
            print(f"{harness}\t{HARNESS_DISPLAY[harness]}\t{agent_target_dir(harness)}\t{TARGET_DIRS[harness][1]}")
        return 0
    if args.check:
        return check(args.repo_root, args.target)
    overrides = load_overrides(args.repo_root)
    if args.deploy or args.dry_run:
        deploy(args.repo_root, args.target, overrides, args.dry_run, args.backup_dir)
        return 0
    written = render_all(args.repo_root, args.out_dir, args.target, overrides)
    for harness, paths in written.items():
        print(f"rendered {harness}: {paths[0].parent} ({len(paths)} agents)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
