#!/usr/bin/env python3
"""Render subagent definitions from agents/*.md into harness-native files.

One source per agent, flat frontmatter, prompt body. The renderer resolves
model tier and effort per harness, maps abstract tool names, injects the hard
invariants, and writes build/agents/<harness>/. Deploy is explicit.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import tomllib
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from tempfile import TemporaryDirectory

from render_invariants import read_invariants
from render_prompts import backup_existing


TIERS = ("cheap", "mid", "flagship", "apex")
EFFORTS = ("low", "medium", "high", "xhigh")
TOOLS = ("read", "search", "edit", "write", "shell", "shell-ro", "web")
WRITE_TOOLS = frozenset({"edit", "write", "shell"})
REQUIRED_KEYS = ("name", "description", "tier", "effort", "tools")
OPTIONAL_KEYS = ("max_turns",)
NAME_RE = re.compile(r"^[a-z][a-z0-9-]*$")

AGENT_HARNESSES = ("claude", "codex", "opencode", "commandcode")
# Command Code silently ignores custom files that reuse a built-in name.
RESERVED_NAMES = {"commandcode": frozenset({"explore", "plan", "review", "general"})}
# These harnesses let a custom agent shadow a built-in; allowed, but noticed.
SHADOWED_NAMES = {
    "codex": frozenset({"default", "worker", "explorer"}),
    "opencode": frozenset({"general", "explore", "scout"}),
}

GENERATED_MARKER = "Generated by render-agents"


@dataclass(frozen=True)
class AgentSpec:
    name: str
    description: str
    tier: str
    effort: str
    tools: tuple[str, ...]
    max_turns: int | None
    body: str
    source: Path
    source_text: str


def parse_frontmatter(text: str, source: Path) -> tuple[dict[str, str], str]:
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        raise SystemExit(f"{source}: missing opening frontmatter delimiter")
    fields: dict[str, str] = {}
    for index in range(1, len(lines)):
        line = lines[index]
        if line.strip() == "---":
            return fields, "".join(lines[index + 1 :])
        if not line.strip():
            continue
        if ":" not in line:
            raise SystemExit(f"{source}: frontmatter line without a colon: {line.strip()}")
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        if key in fields:
            raise SystemExit(f"{source}: duplicate frontmatter key: {key}")
        fields[key] = value
    raise SystemExit(f"{source}: missing closing frontmatter delimiter")


def parse_tools(raw: str, source: Path) -> tuple[str, ...]:
    tools: list[str] = []
    for item in raw.split(","):
        tool = item.strip()
        if not tool:
            continue
        if tool not in TOOLS:
            raise SystemExit(f"{source}: unknown tool '{tool}'; allowed: {', '.join(TOOLS)}")
        if tool not in tools:
            tools.append(tool)
    if not tools:
        raise SystemExit(f"{source}: tools must name at least one tool")
    if "shell" in tools and "shell-ro" in tools:
        raise SystemExit(f"{source}: tools cannot combine shell and shell-ro")
    return tuple(tools)


def load_agent(path: Path) -> AgentSpec:
    text = path.read_text(encoding="utf-8")
    fields, body = parse_frontmatter(text, path)
    for key in REQUIRED_KEYS:
        if key not in fields:
            raise SystemExit(f"{path}: missing key '{key}'")
    for key in fields:
        if key not in REQUIRED_KEYS and key not in OPTIONAL_KEYS:
            raise SystemExit(f"{path}: unknown key '{key}'")

    name = fields["name"]
    if not NAME_RE.match(name):
        raise SystemExit(f"{path}: name '{name}' must match {NAME_RE.pattern}")
    if name != path.stem:
        raise SystemExit(f"{path}: name '{name}' does not match filename stem '{path.stem}'")
    for harness, reserved in RESERVED_NAMES.items():
        if name in reserved:
            raise SystemExit(f"{path}: name '{name}' is reserved by {harness}")

    tier = fields["tier"]
    if tier not in TIERS:
        raise SystemExit(f"{path}: unknown tier '{tier}'; allowed: {', '.join(TIERS)}")
    effort = fields["effort"]
    if effort not in EFFORTS:
        raise SystemExit(f"{path}: unknown effort '{effort}'; allowed: {', '.join(EFFORTS)}")
    description = fields["description"]
    if not description or "\n" in description:
        raise SystemExit(f"{path}: description must be one non-empty line")

    max_turns: int | None = None
    if "max_turns" in fields:
        if not fields["max_turns"].isdigit() or int(fields["max_turns"]) < 1:
            raise SystemExit(f"{path}: max_turns must be a positive integer")
        max_turns = int(fields["max_turns"])

    if not body.strip():
        raise SystemExit(f"{path}: empty prompt body")

    return AgentSpec(
        name=name,
        description=description,
        tier=tier,
        effort=effort,
        tools=parse_tools(fields["tools"], path),
        max_turns=max_turns,
        body=body.strip() + "\n",
        source=path,
        source_text=text,
    )


def load_agents(repo_root: Path) -> list[AgentSpec]:
    agents_dir = repo_root / "agents"
    if not agents_dir.is_dir():
        raise SystemExit(f"Missing agents directory: {agents_dir}")
    specs = [load_agent(path) for path in sorted(agents_dir.glob("*.md"))]
    if not specs:
        raise SystemExit(f"No agent sources found in {agents_dir}")
    return specs
