#!/usr/bin/env python3
"""Render and install the hard-invariants reinforcement artifacts.

One source (prompts/invariants.md), two delivery paths:
  1. Claude Code UserPromptSubmit hook -> re-injects invariants into the main
     loop every turn, surviving context compaction in long sessions.
  2. A paste-in block for subagent definitions -> the hook does not fire on
     subagent dispatches and built-in Explore/Plan agents skip CLAUDE.md, so
     critical rules belong in the agent def itself.

Without --deploy this only writes artifacts under the out dir. With --deploy it
installs the hook and idempotently merges the hook wiring into settings.json,
backing up anything it overwrites. It never edits subagent definitions; that
channel stays a manual paste.
"""
from __future__ import annotations

import argparse
import json
import os
from copy import deepcopy
from pathlib import Path

from render_prompts import backup_existing


HOOK_NAME = "invariants-userpromptsubmit.sh"
SETTINGS_NAME = "claude-settings-snippet.json"
SUBAGENT_NAME = "subagent-block.md"

HOOKS_DIR_ENV = "CLAUDE_HOOKS_DIR"
SETTINGS_PATH_ENV = "CLAUDE_SETTINGS_PATH"
DEFAULT_HOOKS_DIR = "{home}/.claude/hooks"
DEFAULT_SETTINGS_PATH = "{home}/.claude/settings.json"


def read_invariants(repo_root: Path) -> str:
    path = repo_root / "prompts" / "invariants.md"
    if not path.exists():
        raise SystemExit(f"Missing invariants source: {path}")
    return path.read_text(encoding="utf-8").rstrip() + "\n"


def render_hook(invariants: str) -> str:
    # A line equal to the heredoc delimiter would terminate the quoted heredoc
    # early and turn the remaining invariants text into executable shell.
    if any(line.strip() == "INVARIANTS" for line in invariants.splitlines()):
        raise SystemExit(
            "prompts/invariants.md contains a bare 'INVARIANTS' line; "
            "refusing to render the hook heredoc"
        )
    return (
        "#!/usr/bin/env bash\n"
        "# Generated by render-invariants. Do not edit; edit prompts/invariants.md and regenerate.\n"
        "# Claude Code UserPromptSubmit hook: stdout is injected as context each turn.\n"
        "set -euo pipefail\n"
        "cat <<'INVARIANTS'\n"
        f"{invariants}"
        "INVARIANTS\n"
    )


def render_settings_snippet(hook_path: str) -> str:
    return json.dumps(settings_hook_block(hook_path), indent=2) + "\n"


def settings_hook_block(hook_path: str) -> dict:
    return {
        "hooks": {
            "UserPromptSubmit": [
                {"hooks": [{"type": "command", "command": hook_path}]}
            ]
        }
    }


def render_subagent_block(invariants: str) -> str:
    return (
        "<!-- Generated by render-invariants. Paste into custom subagent definitions; "
        "per-turn hooks do not fire for subagents and memory loading varies by agent type. -->\n\n"
        f"{invariants}"
    )


def render_all(repo_root: Path, out_dir: Path, hook_install_path: str) -> dict[str, Path]:
    invariants = read_invariants(repo_root)
    out_dir.mkdir(parents=True, exist_ok=True)

    written: dict[str, Path] = {}

    hook = out_dir / HOOK_NAME
    hook.write_text(render_hook(invariants), encoding="utf-8")
    hook.chmod(0o755)
    written["hook"] = hook

    settings = out_dir / SETTINGS_NAME
    settings.write_text(render_settings_snippet(hook_install_path), encoding="utf-8")
    written["settings"] = settings

    subagent = out_dir / SUBAGENT_NAME
    subagent.write_text(render_subagent_block(invariants), encoding="utf-8")
    written["subagent"] = subagent

    return written


def hook_command_present(settings: dict, command: str) -> bool:
    for entry in settings.get("hooks", {}).get("UserPromptSubmit", []):
        for hook in entry.get("hooks", []):
            if hook.get("command") == command:
                return True
    return False


def merge_hook_into_settings(settings: dict, command: str) -> tuple[dict, bool]:
    """Append our hook entry if absent. Never removes or rewrites existing hooks."""
    merged = deepcopy(settings)
    if hook_command_present(merged, command):
        return merged, False
    hooks = merged.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        raise SystemExit("settings 'hooks' is not an object; refusing to merge")
    ups = hooks.setdefault("UserPromptSubmit", [])
    if not isinstance(ups, list):
        raise SystemExit("settings hooks.UserPromptSubmit is not a list; refusing to merge")
    ups.append({"hooks": [{"type": "command", "command": command}]})
    return merged, True


def load_settings(path: Path) -> dict:
    if not path.exists() or not path.read_text(encoding="utf-8").strip():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(f"settings.json is not valid JSON ({path}): {exc}")
    if not isinstance(data, dict):
        raise SystemExit(f"settings.json root is not an object: {path}")
    return data


def resolve_hooks_dir(home: Path, env: dict[str, str]) -> Path:
    if env.get(HOOKS_DIR_ENV):
        return Path(env[HOOKS_DIR_ENV]).expanduser()
    return Path(DEFAULT_HOOKS_DIR.format(home=home))


def resolve_settings_path(home: Path, env: dict[str, str]) -> Path:
    if env.get(SETTINGS_PATH_ENV):
        return Path(env[SETTINGS_PATH_ENV]).expanduser()
    return Path(DEFAULT_SETTINGS_PATH.format(home=home))


def deploy(
    repo_root: Path,
    hooks_dir: Path,
    settings_path: Path,
    backup_dir: Path,
    dry_run: bool,
) -> None:
    invariants = read_invariants(repo_root)
    hook_dest = hooks_dir / HOOK_NAME
    command = str(hook_dest)

    hook_text = render_hook(invariants)
    settings = load_settings(settings_path)
    merged, changed = merge_hook_into_settings(settings, command)

    if dry_run:
        print(f"would install hook: {hook_dest}")
        if changed:
            print(f"would merge UserPromptSubmit hook into: {settings_path}")
        else:
            print(f"settings already reference the hook: {settings_path}")
        return

    hooks_dir.mkdir(parents=True, exist_ok=True)
    if hook_dest.exists() and hook_dest.read_text(encoding="utf-8") == hook_text:
        print(f"hook unchanged: {hook_dest}")
    else:
        backup_existing(hook_dest, backup_dir)
        hook_dest.write_text(hook_text, encoding="utf-8")
        hook_dest.chmod(0o755)
        print(f"installed hook: {hook_dest}")

    if not changed:
        print(f"settings already reference the hook: {settings_path}")
        return
    settings_path.parent.mkdir(parents=True, exist_ok=True)
    backup_existing(settings_path, backup_dir)
    settings_path.write_text(json.dumps(merged, indent=2) + "\n", encoding="utf-8")
    print(f"merged UserPromptSubmit hook into: {settings_path}")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description="Render and install hard-invariants reinforcement artifacts.")
    parser.add_argument("--repo-root", type=Path, default=repo_root)
    parser.add_argument("--out-dir", type=Path, default=repo_root / "build" / "generated" / "invariants")
    parser.add_argument("--deploy", action="store_true", help="Install the hook and merge settings.json.")
    parser.add_argument("--dry-run", action="store_true", help="Print deploy actions without writing.")
    parser.add_argument("--hooks-dir", type=Path, help=f"Override hooks dir (default: {DEFAULT_HOOKS_DIR}).")
    parser.add_argument("--settings-path", type=Path, help=f"Override settings path (default: {DEFAULT_SETTINGS_PATH}).")
    parser.add_argument("--backup-dir", type=Path, default=repo_root / ".backups", help="Directory for deploy backups.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    home = Path.home()
    hooks_dir = args.hooks_dir or resolve_hooks_dir(home, os.environ)
    settings_path = args.settings_path or resolve_settings_path(home, os.environ)

    if args.deploy or args.dry_run:
        deploy(args.repo_root, hooks_dir, settings_path, args.backup_dir, args.dry_run)
        return 0

    written = render_all(args.repo_root, args.out_dir, str(hooks_dir / HOOK_NAME))
    for label, path in written.items():
        print(f"rendered {label}: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
