#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import shutil
from datetime import date
from pathlib import Path
from typing import NamedTuple


class Harness(NamedTuple):
    name: str
    display: str
    fragment: str
    output_name: str
    target_template: str
    env_var: str


HARNESSES: tuple[Harness, ...] = (
    Harness("claude", "Claude Code", "claude.md", "CLAUDE.md", "{home}/.claude/CLAUDE.md", "CLAUDE_AGENTS_PATH"),
    Harness("codex", "OpenAI Codex", "codex.md", "AGENTS.md", "{home}/AGENTS.md", "CODEX_AGENTS_PATH"),
    Harness("opencode", "OpenCode", "opencode.md", "AGENTS.md", "{home}/.config/opencode/AGENTS.md", "OPENCODE_AGENTS_PATH"),
    Harness("gemini", "Gemini CLI", "gemini.md", "GEMINI.md", "{home}/.gemini/GEMINI.md", "GEMINI_AGENTS_PATH"),
    Harness("cursor", "Cursor", "cursor.md", "AGENTS.md", "{home}/.cursor/AGENTS.md", "CURSOR_AGENTS_PATH"),
    Harness("windsurf", "Windsurf", "windsurf.md", "AGENTS.md", "{home}/.windsurf/AGENTS.md", "WINDSURF_AGENTS_PATH"),
    Harness("copilot", "GitHub Copilot CLI", "copilot.md", "AGENTS.md", "{home}/.copilot/AGENTS.md", "COPILOT_AGENTS_PATH"),
    Harness("aider", "Aider", "aider.md", "AGENTS.md", "{home}/.aider/AGENTS.md", "AIDER_AGENTS_PATH"),
    Harness("goose", "Goose", "goose.md", "AGENTS.md", "{home}/.config/goose/AGENTS.md", "GOOSE_AGENTS_PATH"),
    Harness("amp", "Amp", "amp.md", "AGENTS.md", "{home}/.amp/AGENTS.md", "AMP_AGENTS_PATH"),
    Harness("continue", "Continue", "continue.md", "AGENTS.md", "{home}/.continue/AGENTS.md", "CONTINUE_AGENTS_PATH"),
    Harness("cline", "Cline", "cline.md", "AGENTS.md", "{home}/.cline/AGENTS.md", "CLINE_AGENTS_PATH"),
    Harness("roo", "Roo Code", "roo.md", "AGENTS.md", "{home}/.roo/AGENTS.md", "ROO_AGENTS_PATH"),
    Harness("qwen", "Qwen Code", "qwen.md", "AGENTS.md", "{home}/.qwen/AGENTS.md", "QWEN_AGENTS_PATH"),
    Harness("warp", "Warp", "AGENTS.md", "AGENTS.md", "{home}/.warp/AGENTS.md", "WARP_AGENTS_PATH"),
    Harness("kiro", "Kiro", "kiro.md", "AGENTS.md", "{home}/.kiro/AGENTS.md", "KIRO_AGENTS_PATH"),
    Harness("augment", "Augment", "augment.md", "AGENTS.md", "{home}/.augment/AGENTS.md", "AUGMENT_AGENTS_PATH"),
    Harness("openhands", "OpenHands", "openhands.md", "AGENTS.md", "{home}/.openhands/AGENTS.md", "OPENHANDS_AGENTS_PATH"),
)


def harness_by_name(name: str) -> Harness:
    for harness in HARNESSES:
        if harness.name == name:
            return harness
    supported = ", ".join(harness_names())
    raise SystemExit(f"Unknown harness: {name}. Supported: {supported}")


def harness_names() -> list[str]:
    return [harness.name for harness in HARNESSES]


def selected_harnesses(selected: list[str] | None) -> list[Harness]:
    if not selected:
        return list(HARNESSES)

    names: list[str] = []
    for item in selected:
        names.extend(part.strip() for part in item.split(",") if part.strip())
    return [harness_by_name(name) for name in names]


def target_path(harness: str, home: str | Path | None = None, env: dict[str, str] | None = None) -> Path:
    item = harness_by_name(harness)
    values = os.environ if env is None else env
    if item.env_var in values and values[item.env_var]:
        return Path(values[item.env_var]).expanduser()

    home_path = Path.home() if home is None else Path(home)
    return Path(item.target_template.format(home=home_path)).expanduser()


def render_document(
    harness: str,
    fragment: str,
    core: str,
    private: str = "",
    stamp: str | None = None,
) -> str:
    run_date = stamp or date.today().isoformat()
    rendered = (
        f"<!-- Generated by sync-ai-prompts on {run_date}. "
        "Edit prompts/core.md and prompts/harnesses/*.md, plus optional prompts/private.md "
        "(see prompts/private.example.md), not rendered files. -->\n\n"
        f"{fragment.rstrip()}\n\n"
        f"{core.rstrip()}\n"
    )
    if private.strip():
        rendered += f"\n{private.rstrip()}\n"
    return rendered


def read_fragment(repo_root: Path, harness: Harness) -> str:
    path = repo_root / "prompts" / "harnesses" / harness.fragment
    if not path.exists():
        raise SystemExit(f"Missing fragment for {harness.name}: {path}")
    return path.read_text(encoding="utf-8")


def read_private(repo_root: Path) -> str:
    path = repo_root / "prompts" / "private.md"
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def output_path(out_dir: Path, harness: Harness, collisions: set[str]) -> Path:
    if harness.output_name in collisions:
        return out_dir / harness.name / harness.output_name
    return out_dir / harness.output_name


def render_all(
    repo_root: Path,
    out_dir: Path,
    selected: list[str] | None = None,
    stamp: str | None = None,
) -> dict[str, Path]:
    harnesses = selected_harnesses(selected)
    output_counts: dict[str, int] = {}
    for harness in harnesses:
        output_counts[harness.output_name] = output_counts.get(harness.output_name, 0) + 1
    collisions = {name for name, count in output_counts.items() if count > 1}

    core = (repo_root / "prompts" / "core.md").read_text(encoding="utf-8")
    private = read_private(repo_root)
    written: dict[str, Path] = {}
    for harness in harnesses:
        dest = output_path(out_dir, harness, collisions)
        dest.parent.mkdir(parents=True, exist_ok=True)
        rendered = render_document(
            harness.name,
            read_fragment(repo_root, harness),
            core,
            private=private,
            stamp=stamp,
        )
        dest.write_text(rendered, encoding="utf-8")
        written[harness.name] = dest
    return written


def backup_existing(path: Path, backup_dir: Path) -> None:
    if not path.exists() and not path.is_symlink():
        return
    backup_dir.mkdir(parents=True, exist_ok=True)
    safe_name = str(path).lstrip("/").replace("/", "-")
    backup_stem = f"{path.stem}-{date.today().isoformat()}-{safe_name}"
    backup = backup_dir / f"{backup_stem}.bak"
    counter = 2
    while backup.exists() or backup.is_symlink():
        backup = backup_dir / f"{backup_stem}-{counter}.bak"
        counter += 1
    shutil.copy2(path, backup)


def deploy(
    repo_root: Path,
    selected: list[str] | None,
    stamp: str | None,
    dry_run: bool,
    backup_dir: Path,
) -> dict[str, Path]:
    harnesses = selected_harnesses(selected)
    core = (repo_root / "prompts" / "core.md").read_text(encoding="utf-8")
    private = read_private(repo_root)
    deployed: dict[str, Path] = {}

    for harness in harnesses:
        dest = target_path(harness.name)
        rendered = render_document(
            harness.name,
            read_fragment(repo_root, harness),
            core,
            private=private,
            stamp=stamp,
        )
        deployed[harness.name] = dest
        if dry_run:
            print(f"would update {harness.name}: {dest}")
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        if dest.exists() and dest.read_text(encoding="utf-8", errors="replace") == rendered:
            print(f"unchanged {harness.name}: {dest}")
            continue
        backup_existing(dest, backup_dir)
        dest.write_text(rendered, encoding="utf-8")
        print(f"updated {harness.name}: {dest}")

    return deployed


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description="Render and deploy canonical agent prompt files.")
    parser.add_argument("--repo-root", type=Path, default=repo_root)
    parser.add_argument("--out-dir", type=Path, default=repo_root / "build" / "generated")
    parser.add_argument("--target", action="append", help="Harness target, repeatable or comma-separated.")
    parser.add_argument("--stamp", help="Override generated date, useful for tests.")
    parser.add_argument("--deploy", action="store_true", help="Write rendered files to global harness paths.")
    parser.add_argument("--dry-run", action="store_true", help="Print deploy targets without writing.")
    parser.add_argument("--list-targets", action="store_true", help="List supported harnesses and output paths.")
    parser.add_argument(
        "--backup-dir",
        type=Path,
        default=repo_root / ".backups",
        help="Directory for deploy backups.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if args.list_targets:
        for harness in selected_harnesses(args.target):
            print(f"{harness.name}\t{harness.display}\t{target_path(harness.name)}")
        return 0

    if args.deploy or args.dry_run:
        deploy(args.repo_root, args.target, args.stamp, args.dry_run, args.backup_dir)
        return 0

    written = render_all(args.repo_root, args.out_dir, selected=args.target, stamp=args.stamp)
    for harness, path in written.items():
        print(f"rendered {harness}: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
